swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

    # .env (or override MAILER_URL in .env.local to avoid committing your changes)

# use this to disable email delivery
#MAILER_URL=null://localhost

# use this to configure a traditional SMTP server
#MAILER_URL=smtp://localhost:465?encryption=ssl&auth_mode=login&username=&password=

# username is your full Gmail or Google Apps email address
#MAILER_URL=gmail://ngondogillespatrick:Patr9ckgilles@localhost

