<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJQcGtiO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJQcGtiO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJQcGtiO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJQcGtiO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJQcGtiO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JQcGtiO',
    'container.build_id' => '7cd1a0ed',
    'container.build_time' => 1572926134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJQcGtiO');
