<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0E1ckNk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0E1ckNk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0E1ckNk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0E1ckNk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0E1ckNk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0E1ckNk',
    'container.build_id' => '69fe1f71',
    'container.build_time' => 1568001752,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0E1ckNk');
