<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQb8z9x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQb8z9x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQb8z9x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQb8z9x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXQb8z9x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XQb8z9x',
    'container.build_id' => 'e99879f0',
    'container.build_time' => 1568573931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQb8z9x');
