<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Li7T3xG' shared service.

return $this->privates['.service_locator.Li7T3xG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'trick' => ['privates', '.errored..service_locator.Li7T3xG.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.Li7T3xG": it references class "App\\Entity\\Trick" but no such service exists.'],
], [
    'trick' => 'App\\Entity\\Trick',
]);
