<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vnfTYKf' shared service.

return $this->privates['.service_locator.vnfTYKf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\TickController::add' => ['privates', '.service_locator.ExHSIqn', 'get_ServiceLocator_ExHSIqnService.php', true],
    'App\\Controller\\TickController::edit' => ['privates', '.service_locator.Li7T3xG', 'get_ServiceLocator_Li7T3xGService.php', true],
    'App\\Controller\\UserAccountController::login' => ['privates', '.service_locator.FIoyO0m', 'get_ServiceLocator_FIoyO0mService.php', true],
    'App\\Controller\\TickController:add' => ['privates', '.service_locator.ExHSIqn', 'get_ServiceLocator_ExHSIqnService.php', true],
    'App\\Controller\\TickController:edit' => ['privates', '.service_locator.Li7T3xG', 'get_ServiceLocator_Li7T3xGService.php', true],
    'App\\Controller\\UserAccountController:login' => ['privates', '.service_locator.FIoyO0m', 'get_ServiceLocator_FIoyO0mService.php', true],
], [
    'App\\Controller\\TickController::add' => '?',
    'App\\Controller\\TickController::edit' => '?',
    'App\\Controller\\UserAccountController::login' => '?',
    'App\\Controller\\TickController:add' => '?',
    'App\\Controller\\TickController:edit' => '?',
    'App\\Controller\\UserAccountController:login' => '?',
]);
