<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.63ciB4l' shared service.

return $this->privates['.service_locator.63ciB4l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\CategoryController::delete_name' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\CategoryController:delete_name' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
], [
    'App\\Controller\\CategoryController::delete' => '?',
    'App\\Controller\\CategoryController::delete_name' => '?',
    'App\\Controller\\CategoryController::index' => '?',
    'App\\Controller\\CategoryController::new' => '?',
    'App\\Controller\\CategoryController::show' => '?',
    'App\\Controller\\CategoryController:delete' => '?',
    'App\\Controller\\CategoryController:delete_name' => '?',
    'App\\Controller\\CategoryController:index' => '?',
    'App\\Controller\\CategoryController:new' => '?',
    'App\\Controller\\CategoryController:show' => '?',
]);
